### ISSUE TITLE
Start tag expected error

### ISSUE THREAD

**Issue by ghost** [Shougo/ddu-source-file#2] opened 2022-10-05 15:52 UTC
Hi, I get the following error while calling a ui that includes this file source:
```
Parse error at /home/tyler/.local/share/nvim/site/pack/packer/start/ddu-source-file/denops/@ddu-sources/file.ts:1:1: Start tag expected.
```

I am using ddu-ui-filer with the following config:
```
call ddu#custom#patch_local('filer', {
\   'ui': 'filer',
\   'sources': [
\     {
\       'name': 'file',
\       'params': {},
\     },
\   ],
\   'sourceOptions': {
\     '_': {
\       'columns': ['icon_filename'],
\     },
\   },
\   'uiParams': {
\     'filer': {
\       'winWidth': 40,
\       'split': 'vertical',
\       'splitDirection': 'topleft',
\     }
\   },
\ })

autocmd FileType ddu-filer call s:ddu_filer_my_settings()
function! s:ddu_filer_my_settings() abort
  nnoremap <buffer><silent><expr> <CR>
    \ ddu#ui#filer#is_directory() ?
    \ "<Cmd>call ddu#ui#filer#do_action('expandItem', {'mode': 'toggle'})<CR>" :
    \ "<Cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'open', 'params': {'command': 'vsplit'}})<CR>"

  nnoremap <buffer><silent> q
    \ <Cmd>call ddu#ui#filer#do_action('quit')<CR>
endfunction

nmap <silent> ;d
    \ <Cmd>call ddu#start({'name': 'filer'})<CR>
```

**Comment by Shougo** [comment] 2022-10-06 02:08
I think `/home/tyler/.local/share/nvim/site/pack/packer/start/ddu-source-file/denops/@ddu-sources/file.ts` is broken.
Please check it.

**Comment by Shougo** [comment] 2022-10-06 02:10
You should reinstall `ddu-source-file` plugin.

**Comment by ghost** [comment] 2022-10-06 20:59
> You should reinstall `ddu-source-file` plugin.

I have tried this and it does not work.

**Comment by Shougo** [comment] 2022-10-07 00:44
Really?  Please create the minimal init.vim with the reproduce instruction and upload the full log without `packer.nvim`.
I will try it later.

**Comment by Shougo** [comment] 2022-10-07 00:45
> I think /home/tyler/.local/share/nvim/site/pack/packer/start/ddu-source-file/denops/@ddu-sources/file.ts is broken.
> Please check it.

Please check the file.

**Comment by Shougo** [comment] 2022-10-07 00:46
Hm...  `ddu-source-file` dependency seems broken.  Please update to the latest.

**Comment by ghost** [comment] 2022-10-08 03:24
I have updated, but this has not fixed the error.

I notice that while I get this error, the filer launches but only some folders are shown. Previously, the filer would show my entire file system.

**Comment by Shougo** [comment] 2022-10-08 03:32
Please create the minimal init.vim without packer.nvim.
I will test it later.
Use docker environment is recommend.

**Comment by Shougo** [comment] 2022-10-08 05:25
```vim
set rtp+=~/work/denops.vim
set rtp+=~/work/ddu.vim
set rtp+=~/work/ddu-commands.vim
set rtp+=~/work/ddu-ui-filer
set rtp+=~/work/ddu-kind-file
set rtp+=~/work/ddu-source-file
set rtp+=~/work/ddu-column-filename
set rtp+=~/src/ddu-column-icon_filename

call ddu#custom#patch_local('filer', {
\   'ui': 'filer',
\   'sources': [
\     {
\       'name': 'file',
\       'params': {},
\     },
\   ],
\   'sourceOptions': {
\     '_': {
\       'columns': ['icon_filename'],
\     },
\   },
\   'uiParams': {
\     'filer': {
\       'winWidth': 40,
\       'split': 'vertical',
\       'splitDirection': 'topleft',
\     }
\   },
\ })

autocmd FileType ddu-filer call s:ddu_filer_my_settings()
function! s:ddu_filer_my_settings() abort
  nnoremap <buffer><silent><expr> <CR>
    \ ddu#ui#filer#is_directory() ?
    \ "<Cmd>call ddu#ui#filer#do_action('expandItem', {'mode': 'toggle'})<CR>" :
    \ "<Cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'open', 'params': {'command': 'vsplit'}})<CR>"

  nnoremap <buffer><silent> q
    \ <Cmd>call ddu#ui#filer#do_action('quit')<CR>
endfunction

nmap <silent> ;d
    \ <Cmd>call ddu#start({'name': 'filer'})<CR>
```

It works for me.  So it is your environment problem.  Closing.

**Closed as completed by Shougo** 2022-10-08 05:25 UTC
Labels: invalid
